timeout: 3

# Arka plan rengi (tüm ekran)
backdrop: 1a2b3c

term_background: 802a3b4c
term_foreground: ffffff
term_wallpaper: boot():/boot/limine/boo.png
wallpaper: boot():/boot/limine/boo.png

/AscentOS
    protocol: limine
    path: boot():/boot/kernel
    resolution: 1280x1024